/**
 * Text-quality guard for generated report prose (评审 Spec v2 §4.6 P1-g).
 *
 * v2 testing found corrupted characters in paid report bodies: 「礏盒装」 for
 * 「礼盒装」, 「门店née点计数器」. Nothing in the repository contains those
 * strings, so the corruption is produced at generation time and must be caught
 * before a customer reads it.
 *
 * Two severities, deliberately different in precision:
 *
 *  - `corrupt` — structural damage that is never legitimate output: replacement
 *    characters, private-use / CJK-extension / compatibility ideographs, control
 *    characters, stray combining marks, and Latin fragments glued inside a Han
 *    run (this is what catches 「née」). These are safe to scrub.
 *  - `suspect` — a Han character that appears in neither our own writing
 *    vocabulary (lib/funnel/iq-cjk-vocabulary.json, regenerated by
 *    scripts/build-cjk-vocabulary.mjs) nor the report's own context (address,
 *    cuisine, competitor names…). This is what catches 「礏」. Warn and record;
 *    never scrub, because a legitimate rare character (a restaurant's name) can
 *    land here too.
 */
import vocabulary from './iq-cjk-vocabulary.json';

export type TextQualitySeverity = 'corrupt' | 'suspect';

export interface TextQualityFinding {
  severity: TextQualitySeverity;
  /** Machine-readable reason: replacement_char, private_use, cjk_extension, compatibility_ideograph, control_char, combining_mark, latin_in_han, unknown_han. */
  kind: string;
  /** The offending character or fragment. */
  text: string;
  /** Surrounding text, trimmed, for the log line. */
  context: string;
  /** Index in the scanned string. */
  index: number;
}

export interface TextQualityReport {
  findings: TextQualityFinding[];
  corrupt: number;
  suspect: number;
  /** True when nothing structural was found (suspect findings do not fail). */
  ok: boolean;
}

export interface TextQualityOptions {
  /**
   * Extra text whose Han characters count as legitimate: the address, the
   * business type, competitor names, the market-data blob. Data-borne names are
   * allowed this way instead of by widening the shipped vocabulary.
   */
  context?: string;
  /** Latin terms the product legitimately writes inside Chinese sentences. */
  allowLatin?: string[];
}

const HAN = /\p{Script=Han}/u;
const REPLACEMENT = '�';

/** Latin tokens that legitimately sit inside Chinese sentences in this product. */
const DEFAULT_LATIN_ALLOW = [
  'pdf', 'pos', 'acs', 'go', 'no', 'mi', 'km', 'sqft', 'sf', 'usd', 'ai', 'iq', 'id', 'api', 'url', 'lease', 'hood', 'type',
  'google', 'yelp', 'foursquare', 'loopnet', 'crexi', 'zillow', 'dbi', 'adа', 'ada', 'ok', 'qsr', 'fte', 'hr', 'capex', 'roi',
  'wifi', 'app', 'menu', 'p25', 'p50', 'p75', 'b2b', 'b2c', 'sns', 'ins', 'tiktok', 'whatsapp', 'wechat', 'huff', 'lodes', 'cex',
];

function vocabularySet(): Set<string> {
  return new Set([...(vocabulary as { chars: string }).chars]);
}

let cachedVocabulary: Set<string> | null = null;
function vocab(): Set<string> {
  if (!cachedVocabulary) cachedVocabulary = vocabularySet();
  return cachedVocabulary;
}

function contextAt(text: string, index: number, width = 12): string {
  const start = Math.max(0, index - width);
  const end = Math.min(text.length, index + width);
  return text.slice(start, end).replace(/\s+/g, ' ').trim();
}

/** Characters that are structurally impossible in correct output. */
function structuralKind(ch: string): string | null {
  const cp = ch.codePointAt(0) ?? 0;
  if (ch === REPLACEMENT) return 'replacement_char';
  if (cp >= 0xe000 && cp <= 0xf8ff) return 'private_use';
  if (cp >= 0xf0000) return 'private_use';
  if (cp >= 0xf900 && cp <= 0xfaff) return 'compatibility_ideograph';
  if (cp >= 0x3400 && cp <= 0x4dbf) return 'cjk_extension';
  if (cp >= 0x20000 && cp <= 0x3ffff) return 'cjk_extension';
  // C0/C1 controls except tab / newline / carriage return.
  if ((cp < 0x20 && cp !== 0x09 && cp !== 0x0a && cp !== 0x0d) || (cp >= 0x7f && cp <= 0x9f)) return 'control_char';
  return null;
}

/**
 * A Latin fragment glued between Han characters with no separator — "门店née点".
 * Legitimate inline Latin in our copy is either an allow-listed term, a number,
 * a unit, or is separated by a space or punctuation.
 */
function latinInHanFindings(text: string, allow: Set<string>): TextQualityFinding[] {
  const out: TextQualityFinding[] = [];
  const re = /(\p{Script=Han})([A-Za-zÀ-ɏ]{1,12})(\p{Script=Han})/gu;
  for (const m of text.matchAll(re)) {
    const fragment = m[2];
    if (allow.has(fragment.toLowerCase())) continue;
    const index = (m.index ?? 0) + m[1].length;
    out.push({
      severity: 'corrupt',
      kind: 'latin_in_han',
      text: fragment,
      context: contextAt(text, index),
      index,
    });
  }
  return out;
}

/** A combining mark that did not attach to a base letter (mojibake residue). */
function strayCombiningFindings(text: string): TextQualityFinding[] {
  const out: TextQualityFinding[] = [];
  const re = /(^|[\s\p{Script=Han}\p{P}])(\p{Mn}+)/gu;
  for (const m of text.matchAll(re)) {
    const index = (m.index ?? 0) + m[1].length;
    out.push({ severity: 'corrupt', kind: 'combining_mark', text: m[2], context: contextAt(text, index), index });
  }
  return out;
}

export function scanTextQuality(text: string, opts: TextQualityOptions = {}): TextQualityReport {
  const findings: TextQualityFinding[] = [];
  if (!text) return { findings, corrupt: 0, suspect: 0, ok: true };

  const known = vocab();
  const contextChars = new Set<string>();
  for (const ch of opts.context ?? '') if (HAN.test(ch)) contextChars.add(ch);
  const allowLatin = new Set([...DEFAULT_LATIN_ALLOW, ...(opts.allowLatin ?? []).map((s) => s.toLowerCase())]);

  let index = 0;
  const seenUnknown = new Set<string>();
  for (const ch of text) {
    const kind = structuralKind(ch);
    if (kind) {
      findings.push({ severity: 'corrupt', kind, text: ch, context: contextAt(text, index), index });
    } else if (HAN.test(ch) && !known.has(ch) && !contextChars.has(ch) && !seenUnknown.has(ch)) {
      seenUnknown.add(ch);
      findings.push({ severity: 'suspect', kind: 'unknown_han', text: ch, context: contextAt(text, index), index });
    }
    index += ch.length;
  }
  findings.push(...latinInHanFindings(text, allowLatin));
  findings.push(...strayCombiningFindings(text));

  const corrupt = findings.filter((f) => f.severity === 'corrupt').length;
  const suspect = findings.length - corrupt;
  return { findings, corrupt, suspect, ok: corrupt === 0 };
}

/** One log line per report: what was found, capped so a bad generation cannot flood the log. */
export function formatTextQuality(report: TextQualityReport, max = 6): string {
  if (!report.findings.length) return 'text-quality: clean';
  const head = report.findings
    .slice(0, max)
    .map((f) => `${f.severity}/${f.kind} "${f.text}" …${f.context}…`)
    .join(' | ');
  const more = report.findings.length > max ? ` (+${report.findings.length - max} more)` : '';
  return `text-quality: ${report.corrupt} corrupt, ${report.suspect} suspect — ${head}${more}`;
}

/**
 * Drop sentences that carry structural corruption. Suspect characters are left
 * alone: a rare character in a restaurant's name must survive. Returns the text
 * unchanged when nothing structural was found.
 */
export function scrubCorruptedSentences(text: string, opts: TextQualityOptions = {}): { text: string; removed: number } {
  const report = scanTextQuality(text, opts);
  if (report.ok) return { text, removed: 0 };
  // Split on sentence enders, keeping them attached.
  const parts = text.split(/(?<=[。．.!?！？\n])/);
  let removed = 0;
  const kept = parts.filter((part) => {
    if (!part.trim()) return true;
    const r = scanTextQuality(part, opts);
    if (r.ok) return true;
    removed++;
    return false;
  });
  return { text: kept.join('').replace(/\n{3,}/g, '\n\n').trim(), removed };
}
