import Link from 'next/link';
import { notFound } from 'next/navigation';
import { iqGetReport, iqSetFullReport } from '@/lib/funnel/iq-repository';
import { runFullReport } from '@/lib/funnel/iq-llm';

type FullShape = {
  revenue_estimate?: string;
  risks?: string[];
  opportunities?: string[];
  action_plan?: string[];
  confidence?: string;
};

type Props = {
  params: Promise<{ id: string }>;
};

export default async function IqReportPage({ params }: Props) {
  const { id } = await params;
  const report = await iqGetReport(id);
  if (!report) notFound();

  if (!report.paid) {
    return (
      <main className="flex min-h-screen items-center justify-center px-6">
        <div className="text-center">
          <h1 className="mb-4 text-3xl font-bold">Report locked</h1>
          <p className="mb-6 text-white/70">Payment is required to access the full report.</p>
          <Link href="/iq" className="text-emerald-400 underline">
            Back to analyzer
          </Link>
        </div>
      </main>
    );
  }

  let full = report.full_report_json as FullShape | null;
  if (!full || Object.keys(full).length === 0) {
    try {
      const generated = await runFullReport({
        location: report.location,
        businessType: report.business_type,
        headline: report.headline,
        reason: report.reason,
      });
      await iqSetFullReport(id, generated);
      full = generated as FullShape;
    } catch {
      full = {};
    }
  }

  return (
    <main className="min-h-screen px-6 py-16">
      <div className="mx-auto max-w-3xl space-y-8">
        <div className="rounded-3xl border border-white/10 bg-white/5 p-8">
          <div className="mb-3 text-sm uppercase tracking-[0.2em] text-white/50">RestaurantIQ full report</div>
          <h1 className="mb-3 text-4xl font-bold">{report.headline}</h1>
          <p className="text-white/70">{report.reason}</p>
        </div>
        <div className="grid gap-6">
          <section className="rounded-3xl border border-white/10 bg-white/5 p-6">
            <h2 className="mb-3 text-xl font-semibold">Revenue estimate</h2>
            <p className="text-white/80">{full?.revenue_estimate ?? '—'}</p>
          </section>
          <section className="rounded-3xl border border-white/10 bg-white/5 p-6">
            <h2 className="mb-3 text-xl font-semibold">Top risks</h2>
            <ul className="list-disc space-y-2 pl-6 text-white/80">
              {(full?.risks ?? []).map((r, i) => (
                <li key={i}>{r}</li>
              ))}
            </ul>
          </section>
          <section className="rounded-3xl border border-white/10 bg-white/5 p-6">
            <h2 className="mb-3 text-xl font-semibold">Opportunities</h2>
            <ul className="list-disc space-y-2 pl-6 text-white/80">
              {(full?.opportunities ?? []).map((r, i) => (
                <li key={i}>{r}</li>
              ))}
            </ul>
          </section>
          <section className="rounded-3xl border border-white/10 bg-white/5 p-6">
            <h2 className="mb-3 text-xl font-semibold">Action plan</h2>
            <ol className="list-decimal space-y-2 pl-6 text-white/80">
              {(full?.action_plan ?? []).map((r, i) => (
                <li key={i}>{r}</li>
              ))}
            </ol>
          </section>
          <section className="rounded-3xl border border-white/10 bg-white/5 p-6">
            <h2 className="mb-3 text-xl font-semibold">Confidence</h2>
            <p className="text-white/80">{full?.confidence ?? '—'}</p>
          </section>
        </div>
        <p className="text-center text-sm text-white/30">Generated by RestaurantIQ.ai</p>
      </div>
    </main>
  );
}
