/**
 * Source-gap agent — keeps paid reports from staying "partial" forever.
 *
 * Weekly (app/api/iq/ops?task=source_gaps, Monday 12:00 UTC) it:
 *   a) SCANS paid reports from the last 60 days and counts, per data source
 *      D1..D12, how many carry a `sources[]` row with status partial / failed;
 *   b) FILLS gaps the in-house loaders can fix — D3 (iq_lodes_wac), D5 (iq_poi),
 *      D7 (iq_poi_snapshot): when the table is now loaded, the oldest affected
 *      reports are regenerated (≤ maxReports, cost-capped by the 360° pipeline)
 *      and the new model is committed ONLY when more sources are `ok` than
 *      before and the report does not drop from tier `paid` to `precheck`;
 *   c) DISCOVERS external alternatives for the gaps no loader can fix (D4
 *      isochrones, D7 foot traffic, D8 rent comps, D9 transit ridership, D11
 *      pipeline, Chinese-community signals) with ≤ maxSearches web searches,
 *      scores every hit heuristically (gov / edu / open-data hosts, license
 *      words) and inserts unseen URLs into `iq_source_candidates` as `new` —
 *      never adopted automatically;
 *   d) PERSISTS one `iq_source_gap_runs` row.
 *
 * Never throws; honours `budgetMs`; `dryRun` reads and searches but writes
 * nothing. Every side effect goes through `deps` so the whole flow is
 * unit-tested without network or DB.
 */
import type { WebSearchHit, WebSearchOutcome } from '@/lib/iq/data/rent-comps';
import type { DataSourceId } from '@/lib/iq/data/types';
import type { SourceRow } from '@/lib/iq/model/schema';
import { createBudget, prefixedLog, round4, type OpsBaseOptions, type OpsLog } from './common';

export const ALL_SOURCE_IDS: readonly DataSourceId[] = ['D1', 'D2', 'D3', 'D4', 'D5', 'D6', 'D7', 'D8', 'D9', 'D10', 'D11', 'D12'];

/** Reports younger than this are scanned. */
export const SCAN_WINDOW_DAYS = 60;
/** A report regenerated by this agent is left alone for this long (avoids loops on gaps that never improve). */
export const REGEN_COOLDOWN_DAYS = 30;
/** A regeneration is only started with at least this much budget left (one 360° run ≈ 30–90 s). */
export const REGEN_MIN_REMAINING_MS = 60_000;
/** A web search is only started with at least this much budget left. */
export const SEARCH_MIN_REMAINING_MS = 20_000;
export const DEFAULT_MAX_REPORTS = 3;
export const DEFAULT_MAX_SEARCHES = 3;
/** Hits below this heuristic score are dropped before dedupe / insert. */
export const MIN_CANDIDATE_SCORE = 0.25;
export const MAX_CANDIDATES_PER_SEARCH = 5;
const MAX_REPORTS_SCANNED = 500;

// ───────────────────────────── types ─────────────────────────────

/** `sources[]` row as read back from report_model_json (validated loosely — old rows may predate the schema). */
export interface GapSourceRow {
  id: DataSourceId;
  status: SourceRow['status'];
  coverage_note?: string;
  source?: string;
  degraded_from?: string;
}

export interface GapReport {
  id: string;
  created_at: string;
  /** report_model_json.sources — unknown shape until `normalizeSources` runs. */
  sources: unknown;
  /** report_tier (paid | precheck); null when unknown. */
  tier?: string | null;
}

/** Row counts of the loader-fed tables; 0 = not loaded. */
export interface TableCounts {
  iq_lodes_wac: number;
  iq_poi: number;
  iq_poi_snapshot: number;
}

export interface RegenerateOutcome {
  sources: unknown;
  cost_usd: number;
  tier: string | null;
  /** Persist the regenerated model. Only called when the agent judged it an improvement. */
  commit: () => Promise<void>;
}

export interface SourceCandidateRow {
  gap_source: DataSourceId;
  metro: string;
  title: string;
  url: string;
  publisher: string | null;
  license_hint: string | null;
  coverage_hint: string | null;
  discovered_by: 'web_search';
  score: number;
  status: 'new';
  notes: string | null;
}

export interface SourceGapRunRow {
  run_at: string;
  reports_scanned: number;
  reports_regenerated: number;
  candidates_added: number;
  cost_usd: number;
  notes: Record<string, unknown>;
}

export interface SourceGapDeps {
  /** Paid reports created since `sinceIso` with a report model, oldest first. */
  listReports(sinceIso: string): Promise<GapReport[]>;
  tableCounts(metro: string): Promise<TableCounts>;
  /** Report ids this agent regenerated since `sinceIso` (cooldown). */
  recentRegenerations(metro: string, sinceIso: string): Promise<string[]>;
  /** Run the 360° pipeline WITHOUT persisting; null when the report row is gone. */
  regenerate(reportId: string): Promise<RegenerateOutcome | null>;
  search(query: string): Promise<WebSearchOutcome>;
  /** Subset of `urls` already present in iq_source_candidates. */
  existingCandidateUrls(urls: string[]): Promise<string[]>;
  /** Insert (ignoring url conflicts); returns rows actually written. */
  insertCandidates(rows: SourceCandidateRow[]): Promise<number>;
  insertRun(row: SourceGapRunRow): Promise<void>;
}

export interface MetroProfile {
  label: string;
  counties: string[];
}

export interface SourceGapAgentOptions extends OpsBaseOptions {
  metro: string;
  /** Max reports regenerated per run (default 3). */
  maxReports?: number;
  /** Max web searches per run (default 3). */
  maxSearches?: number;
  deps?: SourceGapDeps;
  /** Overrides METRO_PROFILES (query wording + coverage hints). */
  metroProfile?: MetroProfile;
}

export interface SourceGapAgentResult {
  ok: boolean;
  reason: string | null;
  metro: string;
  reports_scanned: number;
  gaps: Record<DataSourceId, number>;
  table_counts: TableCounts | null;
  /** Report ids whose pipeline was re-run. */
  regenerated: string[];
  /** Subset of `regenerated` whose new model was committed (more `ok` sources). */
  improved: string[];
  /** Dry run: reports that would have been regenerated. */
  would_regenerate: string[];
  searches: number;
  queries: string[];
  candidates_found: number;
  candidates_added: number;
  cost_usd: number;
  notes: string[];
  truncated: boolean;
  elapsed_ms: number;
  dry_run: boolean;
}

// ───────────────────────────── metro + topics ─────────────────────────────

export const METRO_PROFILES: Record<string, MetroProfile> = {
  'sf-bay': {
    label: 'San Francisco Bay Area',
    counties: ['San Mateo County', 'San Francisco', 'Santa Clara County', 'Alameda County', 'Contra Costa County'],
  },
};

export function metroProfile(metro: string): MetroProfile {
  return METRO_PROFILES[metro] ?? { label: metro, counties: [] };
}

export interface DiscoveryTopic {
  source: DataSourceId;
  topic: string;
  /** Relevance words for scoring. */
  keywords: string[];
  /** Searched even when the source shows no gap (after gap-driven topics). */
  always?: boolean;
}

/** Gaps with no in-house loader → look outside. Order = default priority when gap counts tie. */
export const DISCOVERY_TOPICS: readonly DiscoveryTopic[] = [
  { source: 'D4', topic: 'isochrone travel time', keywords: ['isochrone', 'travel time', 'routing', 'drive time'] },
  { source: 'D7', topic: 'foot traffic pedestrian counts', keywords: ['foot traffic', 'pedestrian', 'footfall', 'visits'] },
  { source: 'D8', topic: 'commercial retail lease rates', keywords: ['lease', 'rent', 'asking rate', 'retail space', 'commercial'] },
  { source: 'D9', topic: 'transit ridership station exits', keywords: ['ridership', 'transit', 'station', 'exits', 'boardings'] },
  { source: 'D11', topic: 'development pipeline building permits', keywords: ['permit', 'pipeline', 'development', 'planning', 'entitlement'] },
  { source: 'D2', topic: 'Chinese community population business directory', keywords: ['chinese', 'asian', 'mandarin', 'cantonese', 'community'], always: true },
];

/** Sources a loader in this repo can fix, and the table that must be loaded. */
export const LOADER_SOURCES: Record<'D3' | 'D5' | 'D7', keyof TableCounts> = {
  D3: 'iq_lodes_wac',
  D5: 'iq_poi',
  D7: 'iq_poi_snapshot',
};

// ───────────────────────────── pure helpers ─────────────────────────────

export function emptyGaps(): Record<DataSourceId, number> {
  return Object.fromEntries(ALL_SOURCE_IDS.map((id) => [id, 0])) as Record<DataSourceId, number>;
}

const SOURCE_ID_SET = new Set<string>(ALL_SOURCE_IDS);
const STATUSES = new Set(['ok', 'partial', 'failed']);

/** Keep only rows that look like SourceRow (id D1..D12 + status); tolerate old / malformed JSON. */
export function normalizeSources(raw: unknown): GapSourceRow[] {
  if (!Array.isArray(raw)) return [];
  const out: GapSourceRow[] = [];
  for (const r of raw) {
    if (!r || typeof r !== 'object') continue;
    const o = r as Record<string, unknown>;
    if (typeof o.id !== 'string' || !SOURCE_ID_SET.has(o.id) || typeof o.status !== 'string' || !STATUSES.has(o.status)) continue;
    out.push({
      id: o.id as DataSourceId,
      status: o.status as SourceRow['status'],
      coverage_note: typeof o.coverage_note === 'string' ? o.coverage_note : undefined,
      source: typeof o.source === 'string' ? o.source : undefined,
      degraded_from: typeof o.degraded_from === 'string' ? o.degraded_from : undefined,
    });
  }
  return out;
}

export function okCount(sources: GapSourceRow[]): number {
  return sources.filter((s) => s.status === 'ok').length;
}

/**
 * True when the gap was caused by a loader table being absent / unreachable —
 * i.e. loading the table makes a regeneration worthwhile. A D3 row that is
 * partial because a few tracts have no jobs is NOT fixable this way.
 */
export function loaderFixable(row: GapSourceRow): row is GapSourceRow & { id: keyof typeof LOADER_SOURCES } {
  if (row.status === 'ok') return false;
  const note = `${row.coverage_note ?? ''} ${row.source ?? ''}`;
  switch (row.id) {
    case 'D3':
      return row.status === 'failed' || row.degraded_from === 'lodes_wac' || /iq_lodes_wac\s*(不可达|无)|LODES 未加载/.test(note);
    case 'D5':
      return row.status === 'failed' || /未加载|无记录|not loaded/i.test(note);
    case 'D7':
      return row.status === 'failed' || row.degraded_from === 'snapshot_growth' || /无快照表|未加载|not loaded/i.test(note);
    default:
      return false;
  }
}

/** Dedupe key + stored form: https, lower-case host without `www.`, no hash, no trailing slash. */
export function normalizeUrl(raw: string): string | null {
  try {
    const u = new URL(raw.trim());
    if (u.protocol !== 'http:' && u.protocol !== 'https:') return null;
    const host = u.hostname.toLowerCase().replace(/^www\./, '');
    const path = u.pathname.replace(/\/+$/, '');
    return `https://${host}${path}${u.search}`;
  } catch {
    return null;
  }
}

/** .gov / .mil / .us plus the `<city>gov.org` pattern Bay Area governments use (sfgov.org, smcgov.org, sccgov.org, acgov.org). */
const GOV_HOST_RE = /\.(gov|mil|us)$|gov\.org$/i;
const EDU_HOST_RE = /\.edu$/i;
const ORG_HOST_RE = /\.org$/i;
const OPEN_DATA_HOST_RE = /^data\.|^opendata\.|open-?data|socrata|arcgis|datahub|geoportal|geohub|ckan|catalog/i;
const NOISE_HOST_RE = /(^|\.)(reddit|quora|pinterest|facebook|youtube|linkedin|twitter|x|medium|tiktok|instagram|yelp)\.com$/i;
const LICENSE_RE = /open data|public domain|cc0|cc[- ]by|creative commons|open licen[cs]e|odbl|open government licen[cs]e|freely available|no restrictions/gi;
const DATA_WORDS_RE = /\bapi\b|dataset|\bcsv\b|geojson|shapefile|download|feed/i;
const LISTICLE_RE = /\b(top|best)\s+\d+\b/i;

export interface CandidateScore {
  score: number;
  publisher: string | null;
  license_hint: string | null;
  coverage_hint: string | null;
}

/**
 * Heuristic 0..1: official / open-data hosts and license words up, social /
 * listicle noise down. Deterministic — the operator does the real review.
 */
export function scoreCandidate(hit: WebSearchHit, ctx: { profile: MetroProfile; keywords: string[] }): CandidateScore {
  const url = normalizeUrl(hit.url);
  if (!url) return { score: 0, publisher: null, license_hint: null, coverage_hint: null };
  const host = new URL(url).hostname;
  const text = `${hit.title} ${hit.snippet}`;
  let score = 0.2;
  if (GOV_HOST_RE.test(host)) score += 0.35;
  else if (EDU_HOST_RE.test(host)) score += 0.3;
  else if (ORG_HOST_RE.test(host)) score += 0.1;
  if (OPEN_DATA_HOST_RE.test(host)) score += 0.2;

  const licenseWords = [...new Set([...text.matchAll(LICENSE_RE)].map((m) => m[0].toLowerCase()))];
  if (licenseWords.length) score += 0.15;
  if (DATA_WORDS_RE.test(text)) score += 0.1;

  const places = [ctx.profile.label, ...ctx.profile.counties].filter((p) => p && text.toLowerCase().includes(p.toLowerCase()));
  if (places.length) score += 0.1;
  if (ctx.keywords.some((k) => text.toLowerCase().includes(k.toLowerCase()))) score += 0.1;

  // Social / Q&A hosts are never a data source, whatever words the snippet carries.
  if (NOISE_HOST_RE.test(host)) score -= 0.6;
  if (LISTICLE_RE.test(hit.title)) score -= 0.1;

  return {
    score: Math.round(Math.min(1, Math.max(0, score)) * 100) / 100,
    publisher: host,
    license_hint: licenseWords.length ? licenseWords.join(', ').slice(0, 200) : null,
    coverage_hint: places.length ? places.join(', ').slice(0, 200) : null,
  };
}

/**
 * Query wording alternates week by week (`rotation`) between the two templates;
 * the county template walks the metro's counties in turn (one per odd
 * rotation) so successive runs explore different corners.
 */
export function buildDiscoveryQuery(topic: DiscoveryTopic, profile: MetroProfile, rotation: number): string {
  const r = Math.max(0, Math.floor(rotation));
  const county = profile.counties.length ? profile.counties[Math.floor(r / 2) % profile.counties.length] : null;
  if (r % 2 === 0 || !county) return `open data ${topic.topic} ${profile.label} API dataset`;
  return `${county} open data portal ${topic.topic}`;
}

/** Gap-driven topics first (most gaps first, then declared order), then always-on topics. */
export function selectDiscoveryTopics(gaps: Record<DataSourceId, number>, max: number): DiscoveryTopic[] {
  const withGaps = DISCOVERY_TOPICS.map((t, i) => ({ t, i, n: gaps[t.source] ?? 0 }))
    .filter((x) => x.n > 0)
    .sort((a, b) => b.n - a.n || a.i - b.i)
    .map((x) => x.t);
  const always = DISCOVERY_TOPICS.filter((t) => t.always && !withGaps.includes(t));
  return [...withGaps, ...always].slice(0, Math.max(0, max));
}

function clampInt(v: number | undefined, dflt: number): number {
  return v != null && Number.isFinite(v) && v >= 0 ? Math.floor(v) : dflt;
}

// ───────────────────────────── default deps (Supabase + pipeline) ─────────────────────────────

export function defaultSourceGapDeps(log: OpsLog): SourceGapDeps {
  const supa = async () => (await import('@/lib/server/supabase-admin')).supabaseAdmin();
  return {
    async listReports(sinceIso) {
      const sb = await supa();
      const { data, error } = await sb
        .from('iq_location_reports')
        .select('id,created_at,report_tier,sources:report_model_json->sources')
        .eq('paid', true)
        .not('report_model_json', 'is', null)
        .gte('created_at', sinceIso)
        .order('created_at', { ascending: true })
        .limit(MAX_REPORTS_SCANNED);
      if (error) throw new Error(`iq_location_reports: ${error.message}`);
      const rows = (data ?? []) as unknown as Array<{ id: string; created_at: string; report_tier: string | null; sources: unknown }>;
      return rows.map((r) => ({ id: String(r.id), created_at: String(r.created_at), sources: r.sources, tier: r.report_tier ?? null }));
    },

    async tableCounts(metro) {
      const sb = await supa();
      const count = async (table: keyof TableCounts, byMetro: boolean): Promise<number> => {
        // `estimated` = exact under PostgREST's max-rows, planner estimate above (iq_lodes_wac has millions of rows).
        let q = sb.from(table).select('*', { count: 'estimated', head: true });
        if (byMetro) q = q.eq('metro', metro);
        const { count: n, error } = await q;
        if (error) throw new Error(`${table}: ${error.message}`);
        if ((n ?? 0) > 0) return n as number;
        // A planner estimate can lag a fresh bulk load: confirm emptiness with one row.
        let probe = sb.from(table).select('*').limit(1);
        if (byMetro) probe = probe.eq('metro', metro);
        const { data, error: e2 } = await probe;
        if (e2) throw new Error(`${table}: ${e2.message}`);
        return data?.length ? 1 : 0;
      };
      return { iq_lodes_wac: await count('iq_lodes_wac', false), iq_poi: await count('iq_poi', true), iq_poi_snapshot: await count('iq_poi_snapshot', true) };
    },

    async recentRegenerations(metro, sinceIso) {
      const sb = await supa();
      const { data, error } = await sb.from('iq_source_gap_runs').select('notes').gte('run_at', sinceIso).eq('notes->>metro', metro).limit(200);
      if (error) throw new Error(`iq_source_gap_runs: ${error.message}`);
      const ids: string[] = [];
      for (const row of (data ?? []) as Array<{ notes: { regenerated?: unknown } | null }>) {
        const r = row.notes?.regenerated;
        if (Array.isArray(r)) for (const id of r) if (typeof id === 'string') ids.push(id);
      }
      return ids;
    },

    async regenerate(reportId) {
      const [{ generateReport360ForRow }, { createFetchContext }, { persistCostLog }, { iqSetReportModel }] = await Promise.all([
        import('@/lib/iq/generate'),
        import('@/lib/iq/data/context'),
        import('@/lib/iq/data/cost-log'),
        import('@/lib/funnel/iq-repository'),
      ]);
      const ctx = createFetchContext({ budgetMs: 60_000, log: (m, extra) => log(`[regen ${reportId.slice(0, 8)}] ${m}`, extra) });
      const r = await generateReport360ForRow(reportId, { ctx, persist: false, narrative: true });
      if (!r) return null;
      // Cost is incurred whether or not the model is committed.
      await persistCostLog(reportId, ctx.cost);
      return {
        sources: r.model.sources,
        cost_usd: r.cost_usd,
        tier: r.model.meta.tier,
        commit: async () => {
          const { narrative, ...rest } = r.model;
          await iqSetReportModel({
            reportId,
            reportModelJson: rest as unknown as Record<string, unknown>,
            narrativeJson: narrative,
            tier: r.model.meta.tier,
            costUsd: r.model.meta.cost_usd,
          });
        },
      };
    },

    async search(query) {
      const [{ runWebSearch }, { createFetchContext, createMemoryCache }] = await Promise.all([import('@/lib/iq/data/rent-comps'), import('@/lib/iq/data/context')]);
      const ctx = createFetchContext({ cache: createMemoryCache(), log: () => {}, budgetMs: 20_000 });
      return runWebSearch(query, ctx, { maxResults: 8, costNote: `source-gaps: ${query.slice(0, 60)}` });
    },

    async existingCandidateUrls(urls) {
      if (!urls.length) return [];
      const sb = await supa();
      const { data, error } = await sb.from('iq_source_candidates').select('url').in('url', urls);
      if (error) throw new Error(`iq_source_candidates: ${error.message}`);
      return ((data ?? []) as Array<{ url: string }>).map((r) => r.url);
    },

    async insertCandidates(rows) {
      if (!rows.length) return 0;
      const sb = await supa();
      const { data, error } = await sb.from('iq_source_candidates').upsert(rows, { onConflict: 'url', ignoreDuplicates: true }).select('id');
      if (error) throw new Error(`iq_source_candidates insert: ${error.message}`);
      return data?.length ?? 0;
    },

    async insertRun(row) {
      const sb = await supa();
      const { error } = await sb.from('iq_source_gap_runs').insert(row);
      if (error) throw new Error(`iq_source_gap_runs insert: ${error.message}`);
    },
  };
}

// ───────────────────────────── the agent ─────────────────────────────

export async function runSourceGapAgent(opts: SourceGapAgentOptions): Promise<SourceGapAgentResult> {
  const log = prefixedLog('source-gaps', opts.log);
  const now = opts.now ?? Date.now;
  const budget = createBudget(opts.budgetMs, now);
  const dryRun = Boolean(opts.dryRun);
  const { metro } = opts;
  const maxReports = clampInt(opts.maxReports, DEFAULT_MAX_REPORTS);
  const maxSearches = clampInt(opts.maxSearches, DEFAULT_MAX_SEARCHES);
  const profile = opts.metroProfile ?? metroProfile(metro);
  const startedAt = now();
  const isoAgo = (days: number) => new Date(startedAt - days * 86_400_000).toISOString();

  const notes: string[] = [];
  const note = (m: string) => {
    notes.push(m);
    log(m);
  };
  const res: SourceGapAgentResult = {
    ok: true,
    reason: null,
    metro,
    reports_scanned: 0,
    gaps: emptyGaps(),
    table_counts: null,
    regenerated: [],
    improved: [],
    would_regenerate: [],
    searches: 0,
    queries: [],
    candidates_found: 0,
    candidates_added: 0,
    cost_usd: 0,
    notes,
    truncated: false,
    elapsed_ms: 0,
    dry_run: dryRun,
  };
  const fail = (reason: string) => {
    res.ok = false;
    res.reason = res.reason ?? reason;
    note(`error: ${reason}`);
  };
  const errMsg = (e: unknown) => (e instanceof Error ? e.message : String(e));
  const notImproved: string[] = [];
  const skippedCooldown: string[] = [];

  log(`metro=${metro} window=${SCAN_WINDOW_DAYS}d maxReports=${maxReports} maxSearches=${maxSearches} dry_run=${dryRun} budget=${Number.isFinite(opts.budgetMs ?? NaN) ? Math.round((opts.budgetMs as number) / 1000) + 's' : '∞'}`);

  try {
    const deps = opts.deps ?? defaultSourceGapDeps(log);

    // ── a) scan ──────────────────────────────────────────────────────────
    let reports: Array<GapReport & { rows: GapSourceRow[] }> = [];
    try {
      const raw = await deps.listReports(isoAgo(SCAN_WINDOW_DAYS));
      reports = raw
        .map((r) => ({ ...r, rows: normalizeSources(r.sources) }))
        .sort((a, b) => (a.created_at < b.created_at ? -1 : a.created_at > b.created_at ? 1 : 0));
    } catch (e) {
      fail(`scan failed: ${errMsg(e)}`);
    }
    res.reports_scanned = reports.length;
    for (const r of reports) {
      const seen = new Set<DataSourceId>();
      for (const s of r.rows) {
        if (s.status === 'ok' || seen.has(s.id)) continue;
        seen.add(s.id);
        res.gaps[s.id]++;
      }
    }
    const gapSummary = ALL_SOURCE_IDS.filter((id) => res.gaps[id] > 0).map((id) => `${id}=${res.gaps[id]}`).join(' ');
    log(`scanned ${reports.length} paid reports · gaps: ${gapSummary || 'none'}`);

    // ── b) fill ──────────────────────────────────────────────────────────
    if (res.ok && reports.length) {
      let counts: TableCounts | null = null;
      try {
        counts = await deps.tableCounts(metro);
        res.table_counts = counts;
      } catch (e) {
        note(`fill skipped: table counts unavailable (${errMsg(e)})`);
      }
      if (counts) {
        const loaded = (id: keyof typeof LOADER_SOURCES) => (counts as TableCounts)[LOADER_SOURCES[id]] > 0;
        const fixableIds = (r: { rows: GapSourceRow[] }) => r.rows.filter((s) => loaderFixable(s) && loaded(s.id as keyof typeof LOADER_SOURCES)).map((s) => s.id);
        let cooldown = new Set<string>();
        try {
          cooldown = new Set(await deps.recentRegenerations(metro, isoAgo(REGEN_COOLDOWN_DAYS)));
        } catch (e) {
          note(`cooldown list unavailable (${errMsg(e)}) — regenerating without it`);
        }
        const candidates = reports.filter((r) => fixableIds(r).length > 0);
        const eligible = candidates.filter((r) => {
          if (cooldown.has(r.id)) {
            skippedCooldown.push(r.id);
            return false;
          }
          return true;
        });
        log(`fill: tables lodes=${counts.iq_lodes_wac} poi=${counts.iq_poi} snapshots=${counts.iq_poi_snapshot} · fixable reports=${candidates.length} (cooldown ${skippedCooldown.length}) · cap ${maxReports}`);

        for (const r of eligible.slice(0, maxReports)) {
          const why = fixableIds(r).join('+');
          if (dryRun) {
            res.would_regenerate.push(r.id);
            log(`dry run — would regenerate ${r.id} (${why})`);
            continue;
          }
          if (budget.remaining() < REGEN_MIN_REMAINING_MS) {
            res.truncated = true;
            note(`budget: stopped before regenerating ${r.id} (${Math.round(budget.remaining() / 1000)}s left < ${REGEN_MIN_REMAINING_MS / 1000}s)`);
            break;
          }
          const before = okCount(r.rows);
          try {
            const out = await deps.regenerate(r.id);
            res.regenerated.push(r.id);
            if (!out) {
              note(`${r.id}: report row not found`);
              continue;
            }
            res.cost_usd += out.cost_usd;
            const afterRows = normalizeSources(out.sources);
            const after = okCount(afterRows);
            const downgraded = r.tier === 'paid' && out.tier === 'precheck';
            if (after > before && !downgraded) {
              await out.commit();
              res.improved.push(r.id);
              log(`${r.id}: ${why} → ok sources ${before}→${after}, committed`);
            } else {
              notImproved.push(r.id);
              log(`${r.id}: ${why} → ok sources ${before}→${after}${downgraded ? ' (would drop to precheck)' : ''}, not committed`);
            }
          } catch (e) {
            note(`${r.id}: regeneration failed (${errMsg(e)})`);
          }
        }
      }
    }

    // ── c) discover ──────────────────────────────────────────────────────
    const rotation = Math.floor(startedAt / (7 * 86_400_000));
    const topics = res.ok ? selectDiscoveryTopics(res.gaps, maxSearches) : [];
    const found = new Map<string, SourceCandidateRow>();
    for (const topic of topics) {
      if (budget.remaining() < SEARCH_MIN_REMAINING_MS) {
        res.truncated = true;
        note(`budget: stopped before searching ${topic.source} (${Math.round(budget.remaining() / 1000)}s left)`);
        break;
      }
      const query = buildDiscoveryQuery(topic, profile, rotation);
      res.queries.push(query);
      let out: WebSearchOutcome;
      try {
        out = await deps.search(query);
      } catch (e) {
        note(`search failed (${topic.source}): ${errMsg(e)}`);
        continue;
      }
      res.searches++;
      res.cost_usd += out.cost_usd;
      if (out.error === 'no_key') {
        note('discovery skipped: no TAVILY_API_KEY / BRAVE_SEARCH_API_KEY');
        break;
      }
      if (out.error) {
        note(`search error (${topic.source}, ${out.provider}): ${out.error}`);
        continue;
      }
      const scored = out.hits
        .map((h) => ({ h, url: normalizeUrl(h.url), s: scoreCandidate(h, { profile, keywords: topic.keywords }) }))
        .filter((x): x is { h: WebSearchHit; url: string; s: CandidateScore } => Boolean(x.url) && x.s.score >= MIN_CANDIDATE_SCORE)
        .sort((a, b) => b.s.score - a.s.score);
      let kept = 0;
      for (const x of scored) {
        if (kept >= MAX_CANDIDATES_PER_SEARCH) break;
        if (found.has(x.url)) continue;
        found.set(x.url, {
          gap_source: topic.source,
          metro,
          title: (x.h.title || x.s.publisher || x.url).slice(0, 200),
          url: x.url,
          publisher: x.s.publisher,
          license_hint: x.s.license_hint,
          coverage_hint: x.s.coverage_hint,
          discovered_by: 'web_search',
          score: x.s.score,
          status: 'new',
          notes: `${x.h.snippet.slice(0, 300)}${x.h.snippet ? ' · ' : ''}q: ${query}`.slice(0, 400),
        });
        kept++;
      }
      log(`search ${topic.source} "${query}" → ${out.hits.length} hits, ${kept} kept`);
    }

    let fresh = [...found.values()];
    if (fresh.length) {
      try {
        const existing = new Set(await deps.existingCandidateUrls(fresh.map((c) => c.url)));
        fresh = fresh.filter((c) => !existing.has(c.url));
        if (existing.size) log(`dedupe: ${existing.size} already in iq_source_candidates`);
      } catch (e) {
        note(`dedupe lookup failed (${errMsg(e)}) — relying on the url unique constraint`);
      }
    }
    res.candidates_found = fresh.length;
    if (fresh.length && !dryRun) {
      try {
        res.candidates_added = await deps.insertCandidates(fresh);
      } catch (e) {
        fail(`candidate insert failed: ${errMsg(e)}`);
      }
    } else if (fresh.length) {
      log(`dry run — would insert ${fresh.length} candidates`);
      for (const c of fresh.slice(0, 5)) log(`   ${c.gap_source} ${c.score} ${c.url}`);
    }

    // ── d) persist run ───────────────────────────────────────────────────
    res.cost_usd = round4(res.cost_usd);
    if (!dryRun) {
      try {
        await deps.insertRun({
          run_at: new Date(startedAt).toISOString(),
          reports_scanned: res.reports_scanned,
          reports_regenerated: res.regenerated.length,
          candidates_added: res.candidates_added,
          cost_usd: res.cost_usd,
          notes: {
            metro,
            ok: res.ok,
            gaps: res.gaps,
            table_counts: res.table_counts,
            regenerated: res.regenerated,
            improved: res.improved,
            not_improved: notImproved,
            skipped_cooldown: skippedCooldown,
            queries: res.queries,
            candidates_found: res.candidates_found,
            truncated: res.truncated,
            notes,
          },
        });
      } catch (e) {
        fail(`run row insert failed: ${errMsg(e)}`);
      }
    }
  } catch (e) {
    fail(`unexpected: ${errMsg(e)}`);
  }

  res.cost_usd = round4(res.cost_usd);
  res.elapsed_ms = budget.elapsed();
  log(
    `done · scanned ${res.reports_scanned} · regenerated ${res.regenerated.length} (improved ${res.improved.length}) · searches ${res.searches} · candidates +${res.candidates_added}/${res.candidates_found} · $${res.cost_usd.toFixed(3)} · ${Math.round(res.elapsed_ms / 1000)}s${dryRun ? ' (dry run, nothing written)' : ''}`,
  );
  return res;
}
