'use client';

import { useState } from 'react';
import Link from 'next/link';
import { ReportActions } from './ReportActions';

type FullShape = {
  executive_summary?: string;
  final_verdict?: string;
  trade_area_analysis?: string;
  demographic_profile?: string;
  competition_landscape?: string;
  revenue_estimate?: string;
  risks?: string[];
  opportunities?: string[];
  failure_scenarios?: string[];
  differentiation_strategy?: string;
  action_plan?: string[];
  confidence?: string;
};

type Props = {
  report: {
    id: string;
    location: string;
    business_type: string | null;
    headline: string;
    user_id: string | null;
  };
  full: FullShape;
};

const translations = {
  en: {
    fullReport: 'RestaurantIQ Full Report',
    confidence: 'Confidence',
    businessType: 'Business Type',
    executiveSummary: 'Executive Summary',
    finalVerdict: 'Final Verdict',
    tradeAreaAnalysis: 'Trade Area Analysis',
    demographicProfile: 'Demographic Profile',
    competitionLandscape: 'Competition Landscape',
    revenueEstimate: 'Revenue Estimate',
    topRisks: 'Top Risks',
    opportunities: 'Opportunities',
    failureScenarios: 'Failure Scenarios',
    differentiationStrategy: 'Differentiation Strategy',
    actionPlan: '90-Day Action Plan',
    generatedBy: 'Generated by RestaurantIQ.ai',
    reportId: 'Report ID',
    analyzeAnother: 'Analyze another location',
  },
  zh: {
    fullReport: 'RestaurantIQ 完整报告',
    confidence: '置信度',
    businessType: '业态',
    executiveSummary: '执行摘要',
    finalVerdict: '最终判定',
    tradeAreaAnalysis: '商圈分析',
    demographicProfile: '人口画像',
    competitionLandscape: '竞争格局',
    revenueEstimate: '营收预估',
    topRisks: '主要风险',
    opportunities: '发展机会',
    failureScenarios: '失败场景',
    differentiationStrategy: '差异化策略',
    actionPlan: '90天行动计划',
    generatedBy: '由 RestaurantIQ.ai 生成',
    reportId: '报告编号',
    analyzeAnother: '分析其他地址',
  },
};

function ConfidenceBadge({ level, lang }: { level?: string; lang: 'en' | 'zh' }) {
  const colors: Record<string, string> = {
    High: 'bg-emerald-500/20 text-emerald-300 border-emerald-500/30',
    Medium: 'bg-amber-500/20 text-amber-300 border-amber-500/30',
    Low: 'bg-rose-500/20 text-rose-300 border-rose-500/30',
  };
  const labels: Record<string, Record<string, string>> = {
    en: { High: 'High', Medium: 'Medium', Low: 'Low', Unknown: 'Unknown' },
    zh: { High: '高', Medium: '中', Low: '低', Unknown: '未知' },
  };
  const color = colors[level ?? ''] || 'bg-white/10 text-white/60 border-white/20';
  const label = labels[lang][level ?? ''] || labels[lang].Unknown;
  return (
    <span className={`inline-block rounded-full border px-3 py-1 text-sm font-medium ${color}`}>
      {label} {translations[lang].confidence}
    </span>
  );
}

export function ReportContent({ report, full }: Props) {
  const [lang, setLang] = useState<'en' | 'zh'>('en');
  const t = translations[lang];

  return (
    <>
      {/* Print Styles */}
      <style jsx global>{`
        @media print {
          body {
            background: white !important;
            color: black !important;
            -webkit-print-color-adjust: exact !important;
            print-color-adjust: exact !important;
          }
          .no-print {
            display: none !important;
          }
          .print-only {
            display: block !important;
          }
          main {
            padding: 0 !important;
          }
          .print-section {
            break-inside: avoid;
            page-break-inside: avoid;
          }
          .rounded-3xl, .rounded-2xl, .rounded-xl {
            border-radius: 8px !important;
          }
          .bg-gradient-to-br {
            background: #f0fdf4 !important;
          }
          .bg-white\\/5, .bg-emerald-500\\/10, .bg-rose-500\\/10, .bg-amber-500\\/10, .bg-blue-500\\/10 {
            background: #f9fafb !important;
          }
          .text-white {
            color: #111 !important;
          }
          .text-white\\/70, .text-white\\/80, .text-white\\/60, .text-white\\/50 {
            color: #374151 !important;
          }
          .text-emerald-300, .text-emerald-300\\/70 {
            color: #047857 !important;
          }
          .text-rose-300 {
            color: #dc2626 !important;
          }
          .text-amber-300 {
            color: #d97706 !important;
          }
          .text-blue-300 {
            color: #2563eb !important;
          }
          .border-white\\/10, .border-emerald-500\\/20, .border-rose-500\\/20, .border-amber-500\\/20, .border-blue-500\\/20 {
            border-color: #e5e7eb !important;
          }
        }
        .print-only {
          display: none;
        }
      `}</style>

      {/* Language Toggle - hidden during print */}
      <div className="no-print mb-4 flex justify-end">
        <div className="inline-flex rounded-lg border border-white/20 bg-white/5 p-1">
          <button
            onClick={() => setLang('en')}
            className={`rounded-md px-3 py-1.5 text-sm font-medium transition ${
              lang === 'en' ? 'bg-emerald-500 text-black' : 'text-white/70 hover:text-white'
            }`}
          >
            English
          </button>
          <button
            onClick={() => setLang('zh')}
            className={`rounded-md px-3 py-1.5 text-sm font-medium transition ${
              lang === 'zh' ? 'bg-emerald-500 text-black' : 'text-white/70 hover:text-white'
            }`}
          >
            中文
          </button>
        </div>
      </div>

      {/* Print Header - only visible during print */}
      <div className="print-only mb-8 text-center">
        <h1 className="text-2xl font-bold text-emerald-700">RestaurantIQ</h1>
        <p className="text-sm text-gray-500">Location Intelligence Report</p>
      </div>

      {/* Header */}
      <div className="print-section rounded-3xl border border-emerald-500/20 bg-gradient-to-br from-emerald-900/20 to-emerald-800/10 p-8">
        <div className="mb-4 flex items-center justify-between">
          <div className="text-xs uppercase tracking-[0.25em] text-emerald-300/70">
            {t.fullReport}
          </div>
          <ConfidenceBadge level={full?.confidence} lang={lang} />
        </div>
        <h1 className="mb-4 text-3xl font-bold text-white md:text-4xl">
          {report.headline}
        </h1>
        <p className="text-lg text-white/70">{report.location}</p>
        {report.business_type && (
          <p className="mt-1 text-sm text-white/50">{t.businessType}: {report.business_type}</p>
        )}
      </div>

      {/* Executive Summary */}
      {full?.executive_summary && (
        <div className="print-section rounded-2xl border border-white/10 bg-white/5 p-6">
          <h2 className="mb-3 flex items-center gap-2 text-lg font-semibold text-white">
            <span>📋</span> {t.executiveSummary}
          </h2>
          <p className="text-base leading-relaxed text-white/80">{full.executive_summary}</p>
        </div>
      )}

      {/* Final Verdict */}
      {full?.final_verdict && (
        <div className="print-section rounded-2xl border border-emerald-500/20 bg-emerald-500/10 p-6">
          <h2 className="mb-3 flex items-center gap-2 text-lg font-semibold text-emerald-300">
            <span>✅</span> {t.finalVerdict}
          </h2>
          <p className="text-lg font-medium text-white">{full.final_verdict}</p>
        </div>
      )}

      {/* Trade Area & Demographics */}
      <div className="grid gap-6 md:grid-cols-2">
        {full?.trade_area_analysis && (
          <div className="print-section rounded-2xl border border-white/10 bg-white/5 p-6">
            <h2 className="mb-3 flex items-center gap-2 text-lg font-semibold text-white">
              <span>📍</span> {t.tradeAreaAnalysis}
            </h2>
            <p className="text-sm leading-relaxed text-white/70">{full.trade_area_analysis}</p>
          </div>
        )}
        {full?.demographic_profile && (
          <div className="print-section rounded-2xl border border-white/10 bg-white/5 p-6">
            <h2 className="mb-3 flex items-center gap-2 text-lg font-semibold text-white">
              <span>👥</span> {t.demographicProfile}
            </h2>
            <p className="text-sm leading-relaxed text-white/70">{full.demographic_profile}</p>
          </div>
        )}
      </div>

      {/* Competition & Revenue */}
      <div className="grid gap-6 md:grid-cols-2">
        {full?.competition_landscape && (
          <div className="print-section rounded-2xl border border-white/10 bg-white/5 p-6">
            <h2 className="mb-3 flex items-center gap-2 text-lg font-semibold text-white">
              <span>🏪</span> {t.competitionLandscape}
            </h2>
            <p className="text-sm leading-relaxed text-white/70">{full.competition_landscape}</p>
          </div>
        )}
        {full?.revenue_estimate && (
          <div className="print-section rounded-2xl border border-emerald-500/20 bg-emerald-500/10 p-6">
            <h2 className="mb-3 flex items-center gap-2 text-lg font-semibold text-emerald-300">
              <span>💰</span> {t.revenueEstimate}
            </h2>
            <p className="text-base font-medium text-white">{full.revenue_estimate}</p>
          </div>
        )}
      </div>

      {/* Risks */}
      {full?.risks && full.risks.length > 0 && (
        <div className="print-section rounded-2xl border border-rose-500/20 bg-rose-500/10 p-6">
          <h2 className="mb-4 flex items-center gap-2 text-lg font-semibold text-rose-300">
            <span>⚠️</span> {t.topRisks}
          </h2>
          <ol className="space-y-3">
            {full.risks.map((risk, i) => (
              <li key={i} className="flex gap-3 text-sm text-white/80">
                <span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-rose-500/20 text-xs font-bold text-rose-300">
                  {i + 1}
                </span>
                <span>{risk}</span>
              </li>
            ))}
          </ol>
        </div>
      )}

      {/* Opportunities */}
      {full?.opportunities && full.opportunities.length > 0 && (
        <div className="print-section rounded-2xl border border-emerald-500/20 bg-emerald-500/10 p-6">
          <h2 className="mb-4 flex items-center gap-2 text-lg font-semibold text-emerald-300">
            <span>💡</span> {t.opportunities}
          </h2>
          <ol className="space-y-3">
            {full.opportunities.map((opp, i) => (
              <li key={i} className="flex gap-3 text-sm text-white/80">
                <span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-emerald-500/20 text-xs font-bold text-emerald-300">
                  {i + 1}
                </span>
                <span>{opp}</span>
              </li>
            ))}
          </ol>
        </div>
      )}

      {/* Failure Scenarios */}
      {full?.failure_scenarios && full.failure_scenarios.length > 0 && (
        <div className="print-section rounded-2xl border border-amber-500/20 bg-amber-500/10 p-6">
          <h2 className="mb-4 flex items-center gap-2 text-lg font-semibold text-amber-300">
            <span>🚨</span> {t.failureScenarios}
          </h2>
          <ul className="space-y-3">
            {full.failure_scenarios.map((scenario, i) => (
              <li key={i} className="flex gap-3 text-sm text-white/80">
                <span className="text-amber-400">•</span>
                <span>{scenario}</span>
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* Differentiation Strategy */}
      {full?.differentiation_strategy && (
        <div className="print-section rounded-2xl border border-white/10 bg-white/5 p-6">
          <h2 className="mb-3 flex items-center gap-2 text-lg font-semibold text-white">
            <span>🎯</span> {t.differentiationStrategy}
          </h2>
          <p className="text-sm leading-relaxed text-white/70">{full.differentiation_strategy}</p>
        </div>
      )}

      {/* Action Plan */}
      {full?.action_plan && full.action_plan.length > 0 && (
        <div className="print-section rounded-2xl border border-blue-500/20 bg-blue-500/10 p-6">
          <h2 className="mb-4 flex items-center gap-2 text-lg font-semibold text-blue-300">
            <span>📝</span> {t.actionPlan}
          </h2>
          <ol className="space-y-3">
            {full.action_plan.map((step, i) => (
              <li key={i} className="flex gap-3 text-sm text-white/80">
                <span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-blue-500/20 text-xs font-bold text-blue-300">
                  {i + 1}
                </span>
                <span>{step}</span>
              </li>
            ))}
          </ol>
        </div>
      )}

      {/* PDF Download & Account Actions - hidden during print */}
      <div className="no-print">
        <ReportActions reportId={report.id} isLinkedToUser={!!report.user_id} />
      </div>

      {/* Footer */}
      <div className="text-center">
        <p className="text-sm text-white/30">
          {t.generatedBy} • {t.reportId}: {report.id.slice(0, 8)}
        </p>
        <Link href="/iq" className="no-print mt-4 inline-block text-sm text-emerald-400 hover:underline">
          ← {t.analyzeAnother}
        </Link>
      </div>
    </>
  );
}
