'use client';

import { useCallback, useEffect, useRef, useState } from 'react';
import Link from 'next/link';
import { useAuth } from '@clerk/nextjs';
import { useRouter } from 'next/navigation';
import { ReportActions } from './ReportActions';
import { ReportMarkdown } from './ReportMarkdown';
import { normalizeConfidenceLevel } from '@/lib/funnel/iq-full-report-schema';

type FullReportView = Record<string, unknown>;

type Props = {
  report: {
    id: string;
    location: string;
    business_type: string | null;
    headline: string;
    user_id: string | null;
  };
  full: FullReportView;
  initialLang?: 'en' | 'zh';
};

const translations = {
  en: {
    fullReport: 'RestaurantIQ Premium Analysis',
    confidence: 'Confidence',
    businessType: 'Business Type',
    reportTitle: 'Analysis title',
    dashboard: 'Key metrics',
    executiveSummary: 'Executive Summary',
    finalVerdict: 'Final Verdict',
    tradeAreaAnalysis: 'Trade Area Analysis',
    demographicProfile: 'Demographic Profile',
    competitionLandscape: 'Competition Landscape',
    competitorsTable: 'Competitor matrix',
    revenueEstimate: 'Revenue outlook',
    revenueModel: 'Revenue model & scenarios',
    topRisks: 'Risk matrix',
    opportunities: 'Opportunities',
    failureScenarios: 'Failure scenarios',
    differentiationStrategy: 'Differentiation strategy',
    acquisition: 'Acquisition priorities',
    actionPlan: '90-day action plan',
    actionPlanStructured: 'Structured roadmap',
    comparables: 'Comparable cases',
    decisionMatrix: 'Weighted decision matrix',
    dataSources: 'Data sources & disclaimer',
    generatedBy: 'Generated by RestaurantIQ.ai',
    reportId: 'Report ID',
    analyzeAnother: 'Analyze another location',
    contentNote: '',
    overallScore: 'Overall',
    footTraffic: 'Foot traffic',
    competition: 'Competition',
    payback: 'Payback (mo)',
    recommendation: 'Recommendation',
  },
  zh: {
    fullReport: 'RestaurantIQ 付费深度分析',
    confidence: '置信度',
    businessType: '业态',
    reportTitle: '报告标题',
    dashboard: '关键指标',
    executiveSummary: '执行摘要',
    finalVerdict: '最终判定',
    tradeAreaAnalysis: '贸易区与客流',
    demographicProfile: '人口与消费力',
    competitionLandscape: '竞争格局（叙述）',
    competitorsTable: '竞争对手矩阵',
    revenueEstimate: '营收预估（叙述）',
    revenueModel: '三场景营收模型',
    topRisks: '风险矩阵',
    opportunities: '发展机会',
    failureScenarios: '失败场景',
    differentiationStrategy: '差异化策略',
    acquisition: '获客渠道优先级',
    actionPlan: '90天行动计划',
    actionPlanStructured: '结构化作战表',
    comparables: '可比案例',
    decisionMatrix: '加权决策矩阵',
    dataSources: '数据来源与免责声明',
    generatedBy: '由 RestaurantIQ.ai 生成',
    reportId: '报告编号',
    analyzeAnother: '分析其他地址',
    contentNote: '（部分段落含 Markdown 表格）',
    overallScore: '综合分',
    footTraffic: '客流指数',
    competition: '竞争强度',
    payback: '回收期(月)',
    recommendation: '建议等级',
  },
};

function str(v: unknown): string | undefined {
  return typeof v === 'string' && v.trim() ? v : undefined;
}

function safeArr(v: unknown): unknown[] {
  return Array.isArray(v) ? v : [];
}

function ConfidenceBadge({
  confidence,
  rationale,
  lang,
}: {
  confidence?: string;
  rationale?: string;
  lang: 'en' | 'zh';
}) {
  const level = normalizeConfidenceLevel(confidence);
  const colors: Record<string, string> = {
    High: 'border-emerald-500/40 bg-emerald-500/15 text-emerald-200',
    Medium: 'border-amber-500/40 bg-amber-500/10 text-amber-200',
    Low: 'border-rose-500/40 bg-rose-500/10 text-rose-200',
  };
  const labels: Record<string, Record<string, string>> = {
    en: { High: 'High', Medium: 'Medium', Low: 'Low', Unknown: 'Unknown' },
    zh: { High: '高', Medium: '中', Low: '低', Unknown: '未知' },
  };
  const color = level ? colors[level] : 'border-zinc-600 bg-zinc-800/80 text-zinc-400';
  const label = level ? labels[lang][level] : labels[lang].Unknown;
  return (
    <div className="text-right">
      <span className={`inline-block rounded-full border px-3 py-1 text-sm font-medium ${color}`}>
        {label} {translations[lang].confidence}
      </span>
      {rationale?.trim() && (
        <p className="mt-2 max-w-md text-xs leading-snug text-zinc-500">{rationale}</p>
      )}
    </div>
  );
}

function SectionShell({
  title,
  icon,
  children,
  className = '',
}: {
  title: string;
  icon: string;
  children: React.ReactNode;
  className?: string;
}) {
  return (
    <section
      className={`print-section rounded-2xl border border-zinc-800 bg-zinc-900/50 p-6 shadow-sm ${className}`}
    >
      <h2 className="mb-4 flex items-center gap-2 text-lg font-semibold tracking-tight text-zinc-100">
        <span aria-hidden>{icon}</span>
        {title}
      </h2>
      {children}
    </section>
  );
}

/**
 * After Google OAuth, Clerk session exists but `iq_location_reports.user_id` is still null
 * (only `/iq/success` auto-linked on checkout). Link this paid report to the signed-in user.
 */
function IqReportAutoLink({
  reportId,
  serverUserId,
  onLinked,
}: {
  reportId: string;
  serverUserId: string | null;
  onLinked: () => void;
}) {
  const { isSignedIn, userId, isLoaded } = useAuth();
  const router = useRouter();
  const inFlight = useRef(false);

  useEffect(() => {
    if (!isLoaded || !isSignedIn || !userId) return;
    if (serverUserId === userId) return;
    if (serverUserId && serverUserId !== userId) return;
    if (inFlight.current) return;
    inFlight.current = true;

    void (async () => {
      try {
        const res = await fetch('/api/iq/link-report', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ reportId }),
        });
        if (res.ok) {
          onLinked();
          router.refresh();
        } else {
          inFlight.current = false;
        }
      } catch {
        inFlight.current = false;
      }
    })();
  }, [isLoaded, isSignedIn, userId, serverUserId, reportId, onLinked, router]);

  return null;
}

export function ReportContent({ report, full, initialLang = 'en' }: Props) {
  const [lang, setLang] = useState<'en' | 'zh'>(initialLang);
  const [linkedLocally, setLinkedLocally] = useState(false);
  const handleReportLinked = useCallback(() => setLinkedLocally(true), []);

  const clerkLinkEnabled =
    process.env.NEXT_PUBLIC_USE_MOCK_DATA !== 'true' &&
    Boolean(process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY);

  const t = translations[lang];

  const dashboard = full.dashboard as Record<string, unknown> | undefined;
  const competitors = safeArr(full.competitors);
  const riskMatrix = safeArr(full.risk_matrix);
  const revenueModel = full.revenue_model as Record<string, unknown> | undefined;
  const scenarios = safeArr(revenueModel?.scenarios);
  const sensitivity = safeArr(revenueModel?.sensitivity);
  const acquisition = safeArr(full.acquisition_channels);
  const structuredSteps = safeArr(full.action_plan_structured);
  const decisionMatrix = safeArr(full.decision_matrix);
  const comparables = full.comparables as Record<string, unknown> | undefined;
  const successCases = safeArr(comparables?.success_cases);
  const failureCases = safeArr(comparables?.failure_cases);

  const displayTitle = str(full.report_title) || report.headline;
  const confRaw = str(full.confidence);
  const confRationale = str(full.confidence_rationale);

  const showRevenueModelBlock =
    !!revenueModel &&
    (scenarios.length > 0 || Boolean(str(revenueModel.methodology as string)));
  const showRevenueEstimateBlock = Boolean(str(full.revenue_estimate));
  const showRevenueSection = showRevenueModelBlock || showRevenueEstimateBlock;

  return (
    <>
      {clerkLinkEnabled ? (
        <IqReportAutoLink
          reportId={report.id}
          serverUserId={report.user_id}
          onLinked={handleReportLinked}
        />
      ) : null}
      <style jsx global>{`
        @media print {
          body {
            background: white !important;
            color: #111 !important;
            -webkit-print-color-adjust: exact !important;
            print-color-adjust: exact !important;
          }
          .no-print {
            display: none !important;
          }
          .print-only {
            display: block !important;
          }
          main {
            padding: 0 !important;
          }
          .print-section {
            break-inside: avoid;
            page-break-inside: avoid;
          }
          .rounded-2xl,
          .rounded-3xl,
          .rounded-xl {
            border-radius: 8px !important;
          }
          .border-zinc-800 {
            border-color: #e5e7eb !important;
          }
          .bg-zinc-900\\/50,
          .bg-zinc-950\\/30 {
            background: #fafafa !important;
          }
          .text-zinc-100,
          .text-zinc-200,
          .text-white {
            color: #111 !important;
          }
          .text-zinc-300,
          .text-zinc-400,
          .text-zinc-500 {
            color: #374151 !important;
          }
        }
        .print-only {
          display: none;
        }
      `}</style>

      <div className="no-print mb-4 flex items-center justify-between">
        <div className="text-xs text-zinc-500">{t.contentNote}</div>
        <div className="inline-flex rounded-lg border border-zinc-700 bg-zinc-900/80 p-1">
          <button
            type="button"
            onClick={() => setLang('en')}
            className={`rounded-md px-3 py-1.5 text-sm font-medium transition ${
              lang === 'en' ? 'bg-zinc-100 text-zinc-900' : 'text-zinc-400 hover:text-zinc-200'
            }`}
          >
            English
          </button>
          <button
            type="button"
            onClick={() => setLang('zh')}
            className={`rounded-md px-3 py-1.5 text-sm font-medium transition ${
              lang === 'zh' ? 'bg-zinc-100 text-zinc-900' : 'text-zinc-400 hover:text-zinc-200'
            }`}
          >
            中文
          </button>
        </div>
      </div>

      <div className="print-only mb-8 text-center">
        <h1 className="text-2xl font-bold text-zinc-900">RestaurantIQ</h1>
        <p className="text-sm text-zinc-500">Location Intelligence Report</p>
      </div>

      {/* Header */}
      <header className="print-section rounded-3xl border border-zinc-800 bg-gradient-to-br from-zinc-900 to-zinc-950 p-8">
        <div className="mb-4 flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
          <div className="text-xs uppercase tracking-[0.2em] text-zinc-500">{t.fullReport}</div>
          <ConfidenceBadge confidence={confRaw} rationale={confRationale} lang={lang} />
        </div>
        <h1 className="mb-3 text-3xl font-bold tracking-tight text-zinc-50 md:text-4xl">{displayTitle}</h1>
        <p className="text-lg text-zinc-400">{report.location}</p>
        {report.business_type && (
          <p className="mt-1 text-sm text-zinc-500">
            {t.businessType}: {report.business_type}
          </p>
        )}
      </header>

      {/* Dashboard */}
      {dashboard && Object.keys(dashboard).length > 0 && (
        <SectionShell title={t.dashboard} icon="📊">
          <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">
            {[
              ['overall_score', t.overallScore],
              ['foot_traffic_index', t.footTraffic],
              ['competition_intensity', t.competition],
              ['payback_months', t.payback],
              ['recommendation', t.recommendation],
            ].map(([key, label]) => {
              const val = dashboard[key];
              if (val === undefined || val === null || val === '') return null;
              return (
                <div
                  key={key}
                  className="rounded-xl border border-zinc-800 bg-zinc-950/40 px-4 py-3 text-center"
                >
                  <div className="text-[11px] font-medium uppercase tracking-wide text-zinc-500">{label}</div>
                  <div className="mt-1 text-lg font-semibold text-zinc-100">{String(val)}</div>
                </div>
              );
            })}
          </div>
        </SectionShell>
      )}

      {str(full.executive_summary) && (
        <SectionShell title={t.executiveSummary} icon="📋">
          <ReportMarkdown>{full.executive_summary as string}</ReportMarkdown>
        </SectionShell>
      )}

      {str(full.final_verdict) && (
        <SectionShell title={t.finalVerdict} icon="✅" className="border-emerald-900/40 bg-emerald-950/20">
          <p className="text-lg font-medium text-zinc-100">{full.final_verdict as string}</p>
        </SectionShell>
      )}

      <div className="grid gap-6 md:grid-cols-2">
        {str(full.trade_area_analysis) && (
          <SectionShell title={t.tradeAreaAnalysis} icon="📍">
            <ReportMarkdown>{full.trade_area_analysis as string}</ReportMarkdown>
          </SectionShell>
        )}
        {str(full.demographic_profile) && (
          <SectionShell title={t.demographicProfile} icon="👥">
            <ReportMarkdown>{full.demographic_profile as string}</ReportMarkdown>
          </SectionShell>
        )}
      </div>

      {competitors.length > 0 && (
        <SectionShell title={t.competitorsTable} icon="🏪">
          <div className="overflow-x-auto rounded-lg border border-zinc-800">
            <table className="w-full min-w-[640px] border-collapse text-left text-sm">
              <thead className="bg-zinc-800/60 text-xs uppercase text-zinc-400">
                <tr>
                  <th className="px-3 py-2">#</th>
                  <th className="px-3 py-2">{lang === 'zh' ? '名称' : 'Name'}</th>
                  <th className="px-3 py-2">mi</th>
                  <th className="px-3 py-2">{lang === 'zh' ? '业态' : 'Category'}</th>
                  <th className="px-3 py-2">★</th>
                  <th className="px-3 py-2">{lang === 'zh' ? '评论' : 'Reviews'}</th>
                  <th className="px-3 py-2">{lang === 'zh' ? '价格' : '$'}</th>
                  <th className="px-3 py-2">{lang === 'zh' ? '威胁' : 'Threat'}</th>
                  <th className="px-3 py-2">{lang === 'zh' ? '分析' : 'Note'}</th>
                </tr>
              </thead>
              <tbody className="text-zinc-300">
                {competitors.map((row, i) => {
                  const r = row as Record<string, unknown>;
                  return (
                    <tr key={i} className="border-t border-zinc-800 hover:bg-zinc-800/30">
                      <td className="px-3 py-2 text-zinc-500">{i + 1}</td>
                      <td className="px-3 py-2 font-medium text-zinc-100">{String(r.name ?? '—')}</td>
                      <td className="px-3 py-2">{r.distance_mi != null ? String(r.distance_mi) : '—'}</td>
                      <td className="px-3 py-2">{String(r.category ?? '—')}</td>
                      <td className="px-3 py-2">{r.rating != null ? String(r.rating) : '—'}</td>
                      <td className="px-3 py-2">{r.review_count != null ? String(r.review_count) : '—'}</td>
                      <td className="px-3 py-2">{String(r.price_tier ?? '—')}</td>
                      <td className="px-3 py-2">{String(r.threat_level ?? '—')}</td>
                      <td className="max-w-[220px] px-3 py-2 text-xs text-zinc-400">
                        {String(r.analysis ?? '—')}
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </SectionShell>
      )}

      {str(full.competition_landscape) && (
        <SectionShell title={t.competitionLandscape} icon="🗺️">
          <ReportMarkdown>{full.competition_landscape as string}</ReportMarkdown>
        </SectionShell>
      )}

      {showRevenueSection ? (
        <div className="grid gap-6 lg:grid-cols-2">
          {showRevenueModelBlock && revenueModel ? (
            <SectionShell title={t.revenueModel} icon="📈">
              {str(revenueModel.methodology as string) && (
                <ReportMarkdown className="mb-4">{String(revenueModel.methodology)}</ReportMarkdown>
              )}
              {scenarios.length > 0 && (
                <div className="space-y-3">
                  {scenarios.map((s, i) => {
                    const sc = s as Record<string, unknown>;
                    return (
                      <div
                        key={i}
                        className="rounded-xl border border-zinc-800 bg-zinc-950/40 p-4 text-sm text-zinc-300"
                      >
                        <div className="font-semibold text-zinc-100">
                          {String(sc.name ?? `Scenario ${i + 1}`)}
                          {sc.monthly_revenue_usd != null && sc.monthly_revenue_usd !== '' && (
                            <span className="ml-2 text-emerald-400/90">
                              $
                              {typeof sc.monthly_revenue_usd === 'number'
                                ? sc.monthly_revenue_usd.toLocaleString()
                                : String(sc.monthly_revenue_usd)}
                              /mo
                            </span>
                          )}
                        </div>
                        {str(sc.key_assumptions as string) && (
                          <p className="mt-2 text-xs leading-relaxed text-zinc-400">{String(sc.key_assumptions)}</p>
                        )}
                      </div>
                    );
                  })}
                </div>
              )}
              {sensitivity.length > 0 && (
                <ul className="mt-4 list-disc space-y-1 pl-5 text-sm text-zinc-400">
                  {sensitivity.map((line, i) => (
                    <li key={i}>{String(line)}</li>
                  ))}
                </ul>
              )}
              {str(revenueModel.breakeven as string) && (
                <p className="mt-4 text-sm text-zinc-400">
                  <span className="font-medium text-zinc-300">{lang === 'zh' ? '盈亏平衡：' : 'Breakeven: '}</span>
                  {String(revenueModel.breakeven)}
                </p>
              )}
              {str(revenueModel.monthly_costs_note as string) && (
                <p className="mt-2 text-sm text-zinc-400">
                  <span className="font-medium text-zinc-300">{lang === 'zh' ? '成本结构：' : 'Costs: '}</span>
                  {String(revenueModel.monthly_costs_note)}
                </p>
              )}
            </SectionShell>
          ) : null}
          {showRevenueEstimateBlock ? (
            <SectionShell title={t.revenueEstimate} icon="💰">
              <ReportMarkdown>{full.revenue_estimate as string}</ReportMarkdown>
            </SectionShell>
          ) : null}
        </div>
      ) : null}

      {riskMatrix.length > 0 ? (
        <SectionShell title={t.topRisks} icon="⚠️" className="border-zinc-800">
          <div className="overflow-x-auto rounded-lg border border-zinc-800">
            <table className="w-full min-w-[720px] border-collapse text-left text-sm">
              <thead className="bg-zinc-800/60 text-xs uppercase text-zinc-400">
                <tr>
                  <th className="px-3 py-2">#</th>
                  <th className="px-3 py-2">{lang === 'zh' ? '风险' : 'Risk'}</th>
                  <th className="px-3 py-2">{lang === 'zh' ? '概率' : 'Prob.'}</th>
                  <th className="px-3 py-2">{lang === 'zh' ? '财务影响' : 'Financial'}</th>
                  <th className="px-3 py-2">{lang === 'zh' ? '触发信号' : 'Trigger'}</th>
                  <th className="px-3 py-2">{lang === 'zh' ? '对冲' : 'Mitigation'}</th>
                </tr>
              </thead>
              <tbody className="text-zinc-300">
                {riskMatrix.map((row, i) => {
                  const r = row as Record<string, unknown>;
                  return (
                    <tr key={i} className="border-t border-zinc-800">
                      <td className="px-3 py-2 text-zinc-500">{i + 1}</td>
                      <td className="max-w-[180px] px-3 py-2 font-medium text-zinc-100">{String(r.risk ?? '—')}</td>
                      <td className="px-3 py-2">{String(r.probability ?? '—')}</td>
                      <td className="max-w-[160px] px-3 py-2 text-xs">{String(r.financial_impact ?? '—')}</td>
                      <td className="max-w-[160px] px-3 py-2 text-xs text-zinc-400">{String(r.trigger ?? '—')}</td>
                      <td className="max-w-[200px] px-3 py-2 text-xs text-zinc-400">{String(r.mitigation ?? '—')}</td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </SectionShell>
      ) : (
        safeArr(full.risks).length > 0 && (
          <SectionShell title={t.topRisks} icon="⚠️">
            <ol className="space-y-3">
              {safeArr(full.risks).map((risk, i) => (
                <li key={i} className="flex gap-3 text-sm text-zinc-300">
                  <span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full border border-zinc-700 bg-zinc-800 text-xs font-bold text-zinc-300">
                    {i + 1}
                  </span>
                  <span>{String(risk)}</span>
                </li>
              ))}
            </ol>
          </SectionShell>
        )
      )}

      {safeArr(full.opportunities).length > 0 && (
        <SectionShell title={t.opportunities} icon="💡">
          <ol className="space-y-3">
            {safeArr(full.opportunities).map((opp, i) => (
              <li key={i} className="flex gap-3 text-sm text-zinc-300">
                <span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full border border-zinc-700 bg-zinc-800 text-xs font-bold text-zinc-300">
                  {i + 1}
                </span>
                <span>{String(opp)}</span>
              </li>
            ))}
          </ol>
        </SectionShell>
      )}

      {safeArr(full.failure_scenarios).length > 0 && (
        <SectionShell title={t.failureScenarios} icon="🚨">
          <ul className="space-y-3">
            {safeArr(full.failure_scenarios).map((scenario, i) => (
              <li key={i} className="flex gap-3 text-sm text-zinc-300">
                <span className="text-zinc-500">•</span>
                <span>{String(scenario)}</span>
              </li>
            ))}
          </ul>
        </SectionShell>
      )}

      {str(full.differentiation_strategy) && (
        <SectionShell title={t.differentiationStrategy} icon="🎯">
          <ReportMarkdown>{full.differentiation_strategy as string}</ReportMarkdown>
        </SectionShell>
      )}

      {acquisition.length > 0 && (
        <SectionShell title={t.acquisition} icon="📣">
          <div className="overflow-x-auto rounded-lg border border-zinc-800">
            <table className="w-full min-w-[560px] border-collapse text-left text-sm">
              <thead className="bg-zinc-800/60 text-xs uppercase text-zinc-400">
                <tr>
                  <th className="px-3 py-2">{lang === 'zh' ? '渠道' : 'Channel'}</th>
                  <th className="px-3 py-2">P</th>
                  <th className="px-3 py-2">{lang === 'zh' ? '理由' : 'Why'}</th>
                  <th className="px-3 py-2">CAC</th>
                </tr>
              </thead>
              <tbody className="text-zinc-300">
                {acquisition.map((row, i) => {
                  const r = row as Record<string, unknown>;
                  return (
                    <tr key={i} className="border-t border-zinc-800">
                      <td className="px-3 py-2 font-medium text-zinc-100">{String(r.channel ?? '—')}</td>
                      <td className="px-3 py-2">{String(r.priority ?? '—')}</td>
                      <td className="max-w-[280px] px-3 py-2 text-xs text-zinc-400">{String(r.rationale ?? '—')}</td>
                      <td className="px-3 py-2 text-xs">{String(r.expected_cac_band ?? '—')}</td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </SectionShell>
      )}

      {structuredSteps.length > 0 && (
        <SectionShell title={t.actionPlanStructured} icon="📅">
          <div className="space-y-4">
            {structuredSteps.map((row, i) => {
              const r = row as Record<string, unknown>;
              return (
                <div
                  key={i}
                  className="rounded-xl border border-zinc-800 bg-zinc-950/40 p-4 text-sm text-zinc-300"
                >
                  <div className="font-semibold text-zinc-100">
                    {i + 1}. {String(r.task ?? '—')}
                  </div>
                  <dl className="mt-2 grid gap-1 text-xs text-zinc-400 sm:grid-cols-2">
                    {r.owner != null && r.owner !== '' && (
                      <>
                        <dt className="text-zinc-500">{lang === 'zh' ? '负责人' : 'Owner'}</dt>
                        <dd>{String(r.owner)}</dd>
                      </>
                    )}
                    {r.budget_band != null && r.budget_band !== '' && (
                      <>
                        <dt className="text-zinc-500">{lang === 'zh' ? '预算' : 'Budget'}</dt>
                        <dd>{String(r.budget_band)}</dd>
                      </>
                    )}
                    {r.timeframe != null && r.timeframe !== '' && (
                      <>
                        <dt className="text-zinc-500">{lang === 'zh' ? '时间' : 'Time'}</dt>
                        <dd>{String(r.timeframe)}</dd>
                      </>
                    )}
                    {r.deliverable != null && r.deliverable !== '' && (
                      <>
                        <dt className="text-zinc-500">{lang === 'zh' ? '产出' : 'Deliverable'}</dt>
                        <dd className="sm:col-span-2">{String(r.deliverable)}</dd>
                      </>
                    )}
                    {r.success_metric != null && r.success_metric !== '' && (
                      <>
                        <dt className="text-zinc-500">KPI</dt>
                        <dd className="sm:col-span-2">{String(r.success_metric)}</dd>
                      </>
                    )}
                  </dl>
                </div>
              );
            })}
          </div>
        </SectionShell>
      )}

      {safeArr(full.action_plan).length > 0 && (
        <SectionShell title={t.actionPlan} icon="📝">
          <ol className="space-y-3">
            {safeArr(full.action_plan).map((step, i) => (
              <li key={i} className="flex gap-3 text-sm text-zinc-300">
                <span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full border border-zinc-700 bg-zinc-800 text-xs font-bold text-zinc-300">
                  {i + 1}
                </span>
                <span>{String(step)}</span>
              </li>
            ))}
          </ol>
        </SectionShell>
      )}

      {(successCases.length > 0 || failureCases.length > 0) && (
        <SectionShell title={t.comparables} icon="📚">
          {successCases.length > 0 && (
            <div className="mb-4">
              <h3 className="mb-2 text-sm font-semibold text-emerald-400/90">
                {lang === 'zh' ? '成功案例' : 'Success cases'}
              </h3>
              <ul className="list-disc space-y-2 pl-5 text-sm text-zinc-300">
                {successCases.map((c, i) => (
                  <li key={i}>{String(c)}</li>
                ))}
              </ul>
            </div>
          )}
          {failureCases.length > 0 && (
            <div>
              <h3 className="mb-2 text-sm font-semibold text-rose-400/90">
                {lang === 'zh' ? '失败/关店参考' : 'Failure / closure cases'}
              </h3>
              <ul className="list-disc space-y-2 pl-5 text-sm text-zinc-300">
                {failureCases.map((c, i) => (
                  <li key={i}>{String(c)}</li>
                ))}
              </ul>
            </div>
          )}
        </SectionShell>
      )}

      {decisionMatrix.length > 0 && (
        <SectionShell title={t.decisionMatrix} icon="⚖️">
          <div className="overflow-x-auto rounded-lg border border-zinc-800">
            <table className="w-full min-w-[520px] border-collapse text-left text-sm">
              <thead className="bg-zinc-800/60 text-xs uppercase text-zinc-400">
                <tr>
                  <th className="px-3 py-2">{lang === 'zh' ? '维度' : 'Dimension'}</th>
                  <th className="px-3 py-2">/100</th>
                  <th className="px-3 py-2">%</th>
                  <th className="px-3 py-2">{lang === 'zh' ? '加权' : 'Wtd.'}</th>
                </tr>
              </thead>
              <tbody className="text-zinc-300">
                {decisionMatrix.map((row, i) => {
                  const r = row as Record<string, unknown>;
                  return (
                    <tr key={i} className="border-t border-zinc-800">
                      <td className="px-3 py-2 font-medium text-zinc-100">{String(r.dimension ?? '—')}</td>
                      <td className="px-3 py-2">{r.score_100 != null ? String(r.score_100) : '—'}</td>
                      <td className="px-3 py-2">{r.weight_pct != null ? String(r.weight_pct) : '—'}</td>
                      <td className="px-3 py-2">{r.weighted_score != null ? String(r.weighted_score) : '—'}</td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </SectionShell>
      )}

      {str(full.data_sources_and_disclaimer) && (
        <SectionShell title={t.dataSources} icon="📎">
          <ReportMarkdown>{full.data_sources_and_disclaimer as string}</ReportMarkdown>
        </SectionShell>
      )}

      <div className="no-print">
        <ReportActions
          reportId={report.id}
          isLinkedToUser={Boolean(report.user_id) || linkedLocally}
          lang={lang}
        />
      </div>

      <footer className="text-center">
        <p className="text-sm text-zinc-600">
          {t.generatedBy} • {t.reportId}: {report.id.slice(0, 8)}
        </p>
        <Link href="/iq" className="no-print mt-4 inline-block text-sm text-emerald-500/90 hover:text-emerald-400 hover:underline">
          ← {t.analyzeAnother}
        </Link>
      </footer>
    </>
  );
}
